[package]
name = "qcyx_core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[package.metadata.dist]
dist = false

[dependencies]
qcyx_i18n = { workspace = true }
btleplug = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
cargo-husky = { workspace = true }
